#!/bin/zsh
echo "Limpiando entorno de Laravel..."
echo
echo "Caché de configuración..:"
php artisan config:clear
echo "Caché de enrutamiento..:"
php artisan route:cache
echo "Vistas compiladas..:"
php artisan view:clear
if [ "$?" -eq "0" ]; then
	read -rst 2; timeout=$?
	clear
	echo "Entorno de Laravel limpio"
else
	echo "Ocurrió un error durante el proceso, por favor, verifique"
fi