#!/usr/bin/env zsh

source /home/tureco/Scripts/include/env.sh

declare -g PATHSCRIPT=$0                                                # Capturo la ruta y nombre del script
declare -g SCRIPTNAME=${PATHSCRIPT: -8}                                 # Extraigo el nombre del script de $PATHSCRIPT
declare -g PARAMETERS=${@}                                              # Parámetros que recibe la aplicación

declare -g VERSION="1.0.5"
declare -g UPDATED="2018-04-08 13:22"

declare -g STORAGE="storage"
declare -g BTCACHE="bootstrap/cache"

trap ctrlC INT                                                          # Capturo si se presionó Ctrl-C

unsetVariables() {
    source /home/tureco/Scripts/include/unsetvars.sh
    unsetVars
    # Aquí se hace unset <variable> a cualquier otra variable que exista dentro
    # del script y que no sea estándar dentro de Scripts
}

Main() {
    #---------------------------------------------------------------------------------------------------
    # Ejecuto la función setColors al inicio para que las variables globales de
    # colores y atributos de texto estén disponibles en todo el script.
    source /home/tureco/Scripts/include/setcolors.sh
    setColors
    source /home/tureco/Scripts/include/showmsg.sh
    source /home/tureco/Scripts/include/ctrlc.sh
    source /home/tureco/Scripts/include/headerfooter.sh

    trap ctrlC INT                                                          # Capturo si se presionó Ctrl-C

    setColors

    if [[ ! -d "$STORAGE" || ! -d "$BTCACHE" ]]; then
        showMsg "\n   Los directorios ${FROJO}storage${SCLR} y ${FROJO}bootstrap/cache${SCLR} NO existen!"
        showMsg "\n   Debe usted ubicarse en una ruta real de un proyecto Laravel."
    else
        sudo chgrp -R http storage bootstrap/cache
        sudo chmod -R ug+rwx storage bootstrap/cache
        showMsg "\n   Se cambiaron los permisos a los directorios ${FVRDE}storage${SCLR} y ${FVRDE}bootstrap/cache${SCLR}..."
    fi
    showFooter
}

Main
unsetVariables
