#!/usr/bin/env zsh

printf "Limpiando entorno de Laravel...\n"
printf
printf "Caché de configuración..:\n"
php artisan config:clear
printf "Caché de enrutamiento..:\n"
php artisan route:cache
printf "Vistas compiladas..:\n"
php artisan view:clear
if [ "$?" -eq "0" ]; then
	read -rst 2; timeout=$?
	clear
	printf "Entorno de Laravel limpio\n"
else
	printf "Ocurrió un error durante el proceso, por favor, verifique\n"
fi
